[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[rpc_endpoints]
arb_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
base_sepolia= "https://sepolia.base.org"
arb_mainnet = "https://arbitrum.drpc.org"
base_mainnet = "https://base.drpc.org"
bsc_mainnet = "https://bsc.drpc.org"
kaia_mainnet = "https://klaytn.drpc.org"
pol_mainnet = "https://polygon.drpc.org"

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
